name: eva_sdk
description: This is a SDK for the system https://github.com/eva-ics/eva4
version: 0.2.7
repository: https://github.com/AndreiLosev/eva_sdk

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  busrt_client: ^0.4.0
  msgpack_dart: ^1.0.1
  typed_data: ^1.3.2
  uuid: ^4.3.3
  yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
