name: eva_sdk
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  busrt_client: ^0.1.2
  msgpack_dart: ^1.0.1
  typed_data: ^1.3.2
  uuid: ^4.3.3
  yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
